### ISSUE TITLE
Migration from LocalStorage

### ISSUE THREAD

**Issue by benkaiser** [scryptmouse/Backbone.ChromeStorage#7]
Hello,

This is more of a question and suggestion for the `README` I guess. I currently have an application using backbone and LocalStorage (through `Backbone.LocalStorage`). And my chrome app users have been requesting being able to have the data on all their computers synced. I only did some research today and found your repo and realised it is exactly what I need.

In short my question is, with almost 4000 weekly users of my application (Skill Builder Spelling), is there a way I can migrate to Backbone.ChromeStorage without any loss of data for my users?

My current code (simplified) looks like this:

```
SpellingList = Backbone.Model.extend({
  // utility functions for some manipulation
});
SpellingLists = Backbone.Collection.extend({
  localStorage: new Backbone.LocalStorage('spellingList'),
  model: SpellingList,
  update: function(item){
    // used for saving changes to a list
    this.localStorage.update(item);
  },
  destroy: function(item){
    // deletes an entire list
    this.remove(item);
    this.localStorage.destroy(item);
  }
});
```

and I initialise the data with the following:

```
spellingLists = new SpellingLists();
spellingLists.fetch();
if(spellingLists.length === 0){
 // add some default lists
}
```

Any help would be much appreciated.

**Comment by scryptmouse** [comment]
Probably, since they're both storing things in a similar fashion. I would think you could set up a collection that fetches the models from LocalStorage and pushes the models to a collection that uses ChromeStorage, then have that collection save to persist models to the sync storage.

The models in LS should stick around in the event something goes awry, since adding the model to BB.CS will change its collection and thus where it gets saved. No ideas on the best way to handle potential duplicate objects as users load up the app on their different Chrome browsers, but the migration should be pretty painless otherwise :)

Although, one caveat that I haven't properly addressed is that if you have a lot of frequent create/update/delete actions, you might run into their API limits. In particular, the maximum of ten write operations per minute. I have an idea for how to handle this, but it's still on the todo list. 

http://developer.chrome.com/extensions/storage.html#property-sync-QUOTA_BYTES has more information on the chrome.storage.sync limitations, if they'd even apply.

Very happy to hear this could be useful to you! Please let me know if it works out; it'd make a great wiki page.

**Comment by benkaiser** [comment]
So perhaps I should copy the collection, pull in the lists from localstorage, then migrate them over to chromestorage (if present) then delete them from localstorage (so I don't try and migrate them next time).

Then from then on if there are no objects in localstorage I will assume they are in chromestorage and if there are no objects in chrome storage I will assume they are starting for the first time.

I might try overcome the maximum of 10-per-minute limit by staging the creation of the data (at 1-minute intervals, and deleting each object once it is staged out. The down side is that the user may only see 10 of their 10+ lists at first, but the rest will come through soon).

As for duplicates, I may just count that as a non-issue. Or I may implement a function that loops over the lists when the app loads and checks if all the data is the same in two lists then delete one of them. Only downside is that if there are a lot of lists it will be comparing each list to every other list which I believe is O(N^2) complexity.

I'll get to implementing the code either later tonight or tomorrow and will let you know how I go with it.

**Comment by benkaiser** [comment]
Hey Scryptmouse,

I am trying to debug what is happening to my app, how can I test it without uploading it as a new version of my chrome app? is there a way to test a packaged app before uploading it (I have just been letting apache serve my app, as it is all works as plain javascript, except for chrome storage that is). It might be easier if you email me maybe, my email is benjaminjkaiser (at) gmail (dot) com .

Thanks

**EDIT**: I figured it out, you can load an unpacked extension from the `chrome://extensions` url. I can use that to test the syncing functionality.

**Comment by benkaiser** [comment]
Hey Scryptmouse,

I am having trouble saving data to chromestorage. How exactly do I trigger the update and delete of the models of a collection?

I used to in localstorage have methods that ran:

```
this.localStorage.update(item);
```

or

```
this.localStorage.destroy(item);
```

How do I save the data after modifying or deleting from a collection with the chromestorage plugin?

Thanks

**Comment by scryptmouse** [comment]
Hi Ben,

If you are using the usual Backbone workflow with your models, you shouldn't have to do anything special to delete or update them other than to call `save` or `destroy` on the model itself. It works more like Backbone's default sync functionality since Chrome's storage is asynchronous (whether local or remote), unlike LocalStorage.

If you need extra logic for your save / destroy operations you can hook callbacks into them the same as you would using ajax:

``` javascript
// Second parameter is option callbacks for #save
someModel.save({}, {success: function(model, response, options) {}, error: function(model, xhr, options) {});

// First parameter for #destroy
someModel.destroy({success: function(/* etc */) {}});
```

The Backbone docs have a bit more detail on the callbacks: [Backbone.Model#save](http://backbonejs.org/#Model-save).

Are your models not being properly changed in / removed from `chrome.storage`?
